# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Algorithms Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  # Pods for Algorithms Practice

  target 'Algorithms PracticeTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'Algorithms PracticeUITests' do
    # Pods for testing
    testing_pods
  end

end
